### ISSUE TITLE
lmh ltxlog should be in errors/latexml instead of source/

### ISSUE THREAD

**Issue by m-iancu** [KWARC/localmh#194]
@jucovschi . We discussed this in the mathhub meeting today. The build system puts them there (errors/latexml/*.ltxlog) so it would be nice if lmh used the same convention to avoid confusion.

**Comment by kohlhase** [comment]
how about the mmt errors? Does ```lmh``` put them into the right place as well? Or should that also be changed?

**Comment by m-iancu** [comment]
As far as I know lmh doesn't explicitly move mmt-errors and mmt generates them by default in errors/<compiler>

**Comment by tkw1536** [comment]
@m-iancu @kohlhase I have just tried to implement this, however I now get
```
Fatal:I/O:forbidden Couldn't open log file localmh/MathHub/smglom/smglom/errors/latexml/legendresymbol.de.ltxlog : No such file or directory
```
from latexml which is probably because the errors/latexml/ folder does not exist. I can implement creation in lmh, however I am afraid that this will slow down lmh gen significantly because I will have to do this for every file (and every sub-folder). 

@dginev Is this something that can be fixed in latexml? I. e. when I do 
```
latexmlc file.tex --log=/non/existing/folder/file.ltxlog
```
can latexmlc make sure to create the path and log file?

**Comment by dginev** [comment]
@tkw1536 You are correct, LaTeXML does not create subdirectory structures for the log file at the moment.

It is a reasonable request to add that, please open an issue on the LaTeXML repo.

**Comment by dginev** [comment]
Great news today - Bruce has nicely patched the xml:id inconsistencies with libxml2, and I just synced the KWARC LaTeXML fork with upstream. That sync also brought over the ```--log``` auto-creation of subdirectories. So you should be all set to move forward, just update lmh's LaTeXML.

**Comment by kohlhase** [comment]
indeed great news.

**Comment by tkw1536** [comment]
Sounds like it is fixed then.
