### ISSUE TITLE
reinstate lmh gen --alltex

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#245]
that was very very useful for me. Please reinstate (but not via MMT, reinstate the lmh code proper)

**Comment by tkw1536** [comment]
@cmaeder What is the command to generate all.tex?

**Comment by kohlhase** [comment]
@jfschaefer wants to use this as well.

**Comment by kohlhase** [comment]
I do not really think that MMT does that right?

**Comment by tkw1536** [comment]
all.tex is generated content, so MMT should do it.

**Comment by tkw1536** [comment]
@kohlhase If it has to be python, then the code would need to be completly seperate from ```lmh gen``` since we (essentially) want that to be an alias for ```mmt rbuild```

**Comment by kohlhase** [comment]
I essentially do not care who does that, it seems quite foreign to MMT. I could very well live with ```lmh alltex```.

**Comment by cmaeder** [comment]
MMT does currently not generate `all.tex`. Open an issue if it should.

**Comment by cmaeder** [comment]
MMT has now a target `alltex`, but the generated files are still different (namely without pre- and postamble files, see #59). 

In order to generate `.pdf` from these `all.` files, MMT has also a new target `allpdf`.

(Both targets can be combined into one `alltex_allpdf`, but this is probably not useful for lmh.)

**Comment by cmaeder** [comment]
Well, the `all.` files do include now pre- and postamble files (and `allpdf` or `pdfaltex` detects if these are needed by looking for `\documentclass`)
